services:
  dovecot:
    image: dovecot/dovecot
    container_name: dovecot
    volumes:
      - ./dovecot/conf.d:/etc/dovecot/conf.d
      - ../vmail:/srv/vmail
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - dovecot-auth:/var/spool/postfix/private
    environment:
      - USER_PASSWORD=${USER_PASSWORD}
    ports:
      - "31143:31143"
      - "993:993"
    user: root

  postfix:
    build:
      context: ./postfix
    container_name: postfix
    volumes:
      - dovecot-auth:/var/spool/postfix/private
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - POSTFIX_MYHOSTNAME=${POSTFIX_MYHOSTNAME:-mail.fleetmap.org}
      - POSTFIX_MYDOMAIN=${POSTFIX_MYDOMAIN:-fleetmap.org}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST:-[email-smtp.us-east-1.amazonaws.com]:587}
      - POSTFIX_RELAY_USER=${POSTFIX_RELAY_USER}
      - POSTFIX_RELAY_PASS=${POSTFIX_RELAY_PASS}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - POSTFIX_TLS_CERT_FILE=${POSTFIX_TLS_CERT_FILE:-/etc/letsencrypt/live/mail.fleetmap.org/fullchain.pem}
      - POSTFIX_TLS_KEY_FILE=${POSTFIX_TLS_KEY_FILE:-/etc/letsencrypt/live/mail.fleetmap.org/privkey.pem}
    ports:
      - "587:587"
    depends_on:
      - dovecot

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    volumes:
      - ./roundcube/:/var/roundcube/config/
      - ./autodiscover:/var/www/html/autodiscover:ro
      - ./ios-profiles:/var/www/html/profiles:ro
      - ../vmail:/srv/vmail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=dovecot
      - ROUNDCUBEMAIL_DEFAULT_PORT=31143
      - ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}
      - ROUNDCUBEMAIL_COMPOSER_PLUGINS=radialapps/roundcube-oidc
      - ROUNDCUBEMAIL_PLUGINS=roundcube_oidc
    ports:
      - "8081:80"
    depends_on:
      - dovecot

  lmtp-proxy:
    build:
      context: ./lmtp-proxy
    container_name: lmtp-proxy
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - dovecot

volumes:
  dovecot-auth:
