services:
  dovecot:
    image: dovecot/dovecot
    container_name: dovecot
    volumes:
      - ./dovecot/conf.d:/etc/dovecot/conf.d
      - ./dovecot/mail:/var/mail
    environment:
      - USER_PASSWORD=${USER_PASSWORD}

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    volumes:
      - ./roundcube/config:/var/roundcube/config
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=dovecot
      - ROUNDCUBEMAIL_DEFAULT_PORT=31143
      - ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}
      - ROUNDCUBEMAIL_SMTP_USER=${ROUNDCUBEMAIL_SMTP_USER}
      - ROUNDCUBEMAIL_SMTP_PASS=${ROUNDCUBEMAIL_SMTP_PASS}

    ports:
      - "80:80"
    depends_on:
      - dovecot

  lmtp-proxy:
    build:
      context: ./lmtp-proxy
    container_name: lmtp-proxy
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - dovecot
