auth_mechanisms = plain login
auth_allow_cleartext = yes
doveadm_password = %%doveadm_password%%
ssl = yes
ssl_server_cert_file = /etc/letsencrypt/live/mail.fleetmap.org/fullchain.pem
ssl_server_key_file = /etc/letsencrypt/live/mail.fleetmap.org/privkey.pem

service imap-login {
  inet_listener imap {
    port = 31143
    ssl = no
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service doveadm {
  unix_listener doveadm-server {
    user = vmail
  }
  inet_listener http {
    port = 8081
    ssl = no
  }
}

service lmtp {
  inet_listener lmtp {
    port = 24
  }  
  process_min_avail = 1
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
  }
}

passdb passwd-file {
  passwd_file_path = /srv/vmail/passwd
}
